services:
  shrine-service:
    volumes:
      - ./apps/shrine-service/src:/app/apps/shrine-service/src
      - ./libs:/app/libs
    environment:
      NODE_ENV: development

  api-gateway:
    volumes:
      - ./apps/api-gateway/src:/app/apps/api-gateway/src
      - ./libs:/app/libs
      - ./proto:/app/proto
    environment:
      NODE_ENV: development
