services:
  # Databases
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  shrine-db:
    image: postgres:15-alpine
    container_name: shrine-db
    environment:
      POSTGRES_DB: shrine_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - shrine_db_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  # Microservices
  shrine-service:
    build:
      context: .
      dockerfile: apps/shrine-service/Dockerfile
    container_name: shrine-service
    env_file:
      - .env
    environment:
      DATABASE_HOST: shrine-db
      RABBITMQ_URL: amqp://rabbitmq:5672
      LOCATION_SERVICE_URL: location-service:5006
      NODE_ENV: production
      SHRINE_DATABASE_PORT: 5432
    ports:
      - "5001:5001"
    depends_on:
      - shrine-db
      - location-service
      - rabbitmq
    networks:
      - microservices-network
    volumes:
      - ./proto:/app/proto

  location-service:
    build:
      context: .
      dockerfile: apps/location-service/Dockerfile
    container_name: location-service
    env_file:
      - .env
    environment:
      NODE_ENV: production
      LOCATION_SERVICE_PORT: 5006
      GOOGLE_MAPS_API_KEY: AIzaSyCuYN8_SFYZOxwaXDEjKhsLGuwbn_wLFas
    ports:
      - "5006:5006"
    networks:
      - microservices-network
    volumes:
      - ./proto:/app/proto

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    env_file:
      - .env
    environment:
      SHRINE_SERVICE_URL: shrine-service:5001
      LOCATION_SERVICE_URL: location-service:5006
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      FRONTEND_URL: http://localhost:5173
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - shrine-service
      - location-service
    networks:
      - microservices-network
    volumes:
      - ./proto:/app/proto

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - shrine-db
    networks:
      - microservices-network

volumes:
  shrine_db_data:

networks:
  microservices-network:
    driver: bridge
