apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices
data:
  NODE_ENV: 'production'
  RABBITMQ_URL: 'amqp://rabbitmq:5672'
  RABBITMQ_DEFAULT_USER: 'guest'
  RABBITMQ_DEFAULT_PASS: 'guest'
  # Database hosts
  SHRINE_DATABASE_HOST: 'shrine-db'
  SHRINE_DATABASE_PORT: '5432'
  USER_DATABASE_HOST: 'user-db'
  USER_DATABASE_PORT: '5432'
  WISHING_DATABASE_HOST: 'wishing-db'
  WISHING_DATABASE_PORT: '5432'
  RATING_DATABASE_HOST: 'rating-db'
  RATING_DATABASE_PORT: '5432'
  # Service URLs
  SHRINE_SERVICE_URL: 'shrine-service:5001'
  TECHNIQUE_SERVICE_URL: 'http://technique-service:5002'
  SHRINE_DISCOVERY_SERVICE_URL: 'shrine-discovery-service:5003'
  WISHING_SERVICE_URL: 'wishing-service:5004'
  USER_SERVICE_URL: 'user-service:5005'
  LOCATION_SERVICE_URL: 'location-service:5006'
  RATING_SERVICE_URL: 'rating-service:5007'
  # Ports
  GATEWAY_PORT: '3000'
  SHRINE_GRPC_PORT: '5001'
  TECHNIQUE_HTTP_PORT: '5002'
  SHRINE_DISCOVERY_GRPC_PORT: '5003'
  WISHING_GRPC_PORT: '5004'
  USER_GRPC_PORT: '5005'
  LOCATION_GRPC_PORT: '5006'
  RATING_GRPC_PORT: '5007'
  FRONTEND_URL: 'http://localhost:30002'
