apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgres'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'postgres'
  TECHNIQUE_DATABASE_URI: 'mongodb+srv://admin:m7I4P8xuomEIxZx3@cluster0.bymat5i.mongodb.net/'
  SHRINE_DISCOVERY_DATABASE_URI: 'mongodb+srv://admin:m7I4P8xuomEIxZx3@cluster0.bymat5i.mongodb.net/'
  # JWT Secret - CHANGE THIS IN PRODUCTION
  JWT_SECRET: 'cr2YO0XOTY9t9Ijc6k59NU7KUnwn29uvIwzNfKXuiMItC+rAAOeDcDPjl6iq9+O+w9218kt584Zb5FwjWsDqYw=='
  # Google OAuth
  GOOGLE_CLIENT_ID: '287539575994-ode8cadhfv1nmbvj78jcuagrohflcgrc.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: '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'
  GOOGLE_CALLBACK_URL: 'http://localhost:30000/auth/google/callback'
  # Google Maps API
  GOOGLE_MAPS_API_KEY: 'AIzaSyCuYN8_SFYZOxwaXDEjKhsLGuwbn_wLFas'
  # PgAdmin
  PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
  PGADMIN_DEFAULT_PASSWORD: 'admin'
