apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgres'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'postgres'
  # JWT Secret - CHANGE THIS IN PRODUCTION
  JWT_SECRET: 'cr2YO0XOTY9t9Ijc6k59NU7KUnwn29uvIwzNfKXuiMItC+rAAOeDcDPjl6iq9+O+w9218kt584Zb5FwjWsDqYw=='
  # PgAdmin
  PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
  PGADMIN_DEFAULT_PASSWORD: 'admin'
